ModelH2: 1 #Flag to turn or off Hydrogen Supply Chain modelling capabilities - 0 - no HSC, 1- HSC modeled
H2PipeInteger: 0 # Whether to model pipeline capacity as discrete or integer - 0 - continuous capacity, 1- discrete capacity
ModelH2Pipelines: 0 # Whether to model pipeline in hydrogen supply chain - 0 - not included, 1 - included
ModelH2Trucks: 0 # Whether to model truck in hydrogen supply chain - 0 - not included, 1 - included
H2TrucksMaxDistance: 500 # the max number of miles or km for a truck route (depends on the units used throughout, calculated via time constraint based on truck speed)
ModelH2Liquid: 0 # Whether to model liquefaction (and evaporation) in hydrogen supply chain - 0 - not included, 1 - included
ModelH2G2P: 0 # Whether to model G2P in hydrogen supply chain - 0 - not included, 1 - included
H2GenCommit: 0 # Continuous or discrete capacity representation of H2 production technologies with unit commitment; 0 = modeled as continuous variables; 1 = modeled as integer variables;
H2NetworkExpansion: 0 # Transmission network expansional; 0 = not active; 1 = active systemwide
H2G2PCommit: 0 #1 for unit commitment G2P representation, 0 continuous representation of H2 G2P tech
TimeMatchingRequirement: 3 # Modeling time matching requiremnet for electricity based H2 production - 0 - not included, 1 - hourly with excess sales, 2- hourly without excess sales, 3 - annual 
TMRSalestoESR: 0 #Excess TMR sales can be used to meet ESR requirements
H2TMR_slack_cost: 500 #Slack for TMR constraint
#H2TMR_Excess_Sales_Allowance: .2 #Excess sales allowance for TMR constraint

